[package]
name = "multitag"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "1.14.0"
thiserror = "1.0.63"
metaflac = { git = "ssh://git@github.com/hungl6844/rust-metaflac.git" }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
wildcard_imports = "allow"
# this is temporary, remove this line once we're actually writing docs
missing_errors_doc = "allow"
